sources:
- category: AI 资讯
  feed_url: https://www.latent.space/feed
  max_episodes: 3
  name: Latent Space
  type: rss
- category: 访谈
  feed_url: https://lexfridman.com/feed/podcast/
  max_episodes: 3
  name: Lex Fridman Podcast
  type: rss
- category: 访谈
  feed_url: https://www.dwarkesh.com/feed
  max_episodes: 3
  name: Dwarkesh Podcast
  type: rss
- category: AI 工程
  channel_handle: aiDotEngineer
  max_episodes: 3
  name: AI Engineer
  type: youtube_channel
- category: 创投
  channel_handle: ycombinator
  max_episodes: 3
  name: YC Lightcone
  title_filter: Lightcone
  type: youtube_channel
- category: 产品
  channel_handle: LennysPodcast
  lock_category: true
  max_episodes: 3
  name: Lenny's Podcast
  type: youtube_channel
- category: 投资
  channel_handle: ILTB_Podcast
  lock_category: true
  max_episodes: 3
  name: Invest Like the Best
  type: youtube_channel
